import { test } from "node:test";
import assert from "node:assert/strict";
import { collect, type CollectorRepository } from "../lib/collector";
import { makeDemo } from "../lib/demo";
import { type Observation } from "../lib/growth";
import { YouTubeClient } from "../lib/youtube";
function fixture(at: string) {
  const data = makeDemo(); data.videos = [data.videos[0]]; data.videos[0].publishedAt = "2026-09-01T00:00:00.000Z"; data.observations = []; data.analytics = [];
  const saved: Observation[] = [], log: string[] = []; let released = false;
  const repo: CollectorRepository = { state: async () => structuredClone(data), observation: async (_, o) => { if (saved.some(s => s.videoId === o.videoId && s.checkpoint === o.checkpoint)) return false; saved.push(o); return true; }, updateVideo: async (_, v) => { data.videos[0] = v; }, analytics: async () => {}, lastAnalyticsAttempt: async () => null, markAnalyticsAttempt: async () => {}, acquire: async () => true, release: async () => { released = true; }, recordRun: async (_, summary) => { log.push(summary); } };
  const cfg = { apiKey: "key", channelId: data.videos[0].channelId, clientId: "", clientSecret: "", refreshToken: "" };
  const youtube = new YouTubeClient(cfg);
  youtube.videoMetadata = async () => [{ id: data.videos[0].youtubeId, channelId: cfg.channelId, title: "test", publishedAt: data.videos[0].publishedAt, duration: 38, privacy: "public", live: "none", views: 2400, likes: null }];
  return { data, saved, log, repo, youtube, clock: () => new Date(at), released: () => released };
}
test("collector records missed windows and only uses actual due-time counts", async () => { const f = fixture("2026-09-04T00:01:00Z"); const r = await collect("owner", f.repo, f.youtube, f.clock); assert.equal(r.collected, 1); assert.equal(r.missed, 3); assert.equal(f.saved.find(o => o.checkpoint === "72h")!.views, 2400); assert.equal(f.saved.find(o => o.checkpoint === "1h")!.views, null); assert.equal(f.released(), true); });
test("retrying collection cannot replace an immutable checkpoint", async () => { const f = fixture("2026-09-04T00:01:00Z"); await collect("owner", f.repo, f.youtube, f.clock); f.youtube.videoMetadata = async () => [{ id: f.data.videos[0].youtubeId, channelId: f.youtube.config.channelId, title: "test", publishedAt: f.data.videos[0].publishedAt, duration: 38, privacy: "public", live: "none", views: 999999, likes: 5 }]; await collect("owner", f.repo, f.youtube, f.clock); assert.equal(f.saved.filter(o => o.checkpoint === "72h").length, 1); assert.equal(f.saved.find(o => o.checkpoint === "72h")!.views, 2400); });
test("API failures within a window are retryable, not zero or prematurely missed", async () => { const f = fixture("2026-09-04T00:01:00Z"); f.youtube.videoMetadata = async () => { throw new Error("network"); }; const r = await collect("owner", f.repo, f.youtube, f.clock); assert.equal(r.errors.length, 1); assert.equal(f.saved.some(o => o.checkpoint === "72h"), false); assert.equal(f.released(), true); });
test("statistics received after the deadline are marked missing", async () => { const f = fixture("2026-09-04T01:59:59Z"); let current = f.clock(); f.youtube.videoMetadata = async () => { current = new Date("2026-09-04T02:00:01Z"); return [{ id: f.data.videos[0].youtubeId, channelId: f.youtube.config.channelId, title: "test", publishedAt: f.data.videos[0].publishedAt, duration: 38, privacy: "public", live: "none", views: 999, likes: 5 }]; }; await collect("owner", f.repo, f.youtube, () => current); assert.equal(f.saved.find(o => o.checkpoint === "72h")!.status, "missed"); });
test("changed publication metadata invalidates the video instead of shifting its age", async () => { const f = fixture("2026-09-04T00:01:00Z"); f.youtube.videoMetadata = async () => [{ id: f.data.videos[0].youtubeId, channelId: f.youtube.config.channelId, title: "test", publishedAt: "2026-09-02T00:00:00.000Z", duration: 38, privacy: "public", live: "none", views: 999, likes: 5 }]; await collect("owner", f.repo, f.youtube, f.clock); assert.equal(f.data.videos[0].verified, false); assert.equal(f.saved.some(o => o.checkpoint === "72h"), false); });
test("a concurrent collector does not send duplicate upstream requests", async () => { const f = fixture("2026-09-04T00:01:00Z"); f.repo.acquire = async () => false; f.youtube.videoMetadata = async () => { assert.fail("must not fetch"); }; const r = await collect("owner", f.repo, f.youtube, f.clock); assert.equal(r.collected, 0); assert.equal(f.saved.length, 0); });
