import { test } from "node:test";
import assert from "node:assert/strict";
import { makeDemo } from "../lib/demo";
import { CHECKPOINTS, VIEW_DEFINITION, checkpointState, compare, median } from "../lib/growth";
const now = new Date("2026-09-13T00:00:00Z");
function fixture() { const d = makeDemo(); d.observations.forEach(o => o.source = "youtube_data"); return d; }
function result(d = fixture()) { return compare(d.experiments[0], d, "youtube_data", now); }

test("median uses all samples and never mutates input", () => { const values = [50, 2, 3, 1]; assert.equal(median(values), 2.5); assert.deepEqual(values, [50, 2, 3, 1]); assert.equal(median([]), null); });
test("balanced demo produces an evidence-backed retest, not a publishing permission", () => { const r = result(); assert.equal(r.status, "retest_candidate"); assert.equal(r.candidate, "B"); assert.equal(r.groups[0].median, 1300); assert.equal(r.groups[1].median, 2000); assert.equal(r.groups[0].observationIds.length, 4); assert.deepEqual(r.permissions, { publish: false, paidGeneration: false }); });
test("demo cannot be mixed into real measurements", () => { const r = result(makeDemo()); assert.equal(r.status, "insufficient_data"); assert.equal(r.groups[0].count, 0); });
test("missing view count is excluded, not zero", () => { const d = fixture(); d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!.views = null; assert.equal(result(d).groups[0].count, 3); assert.equal(result(d).status, "insufficient_data"); });
test("an observed zero is still a valid sample", () => { const d = fixture(); d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!.views = 0; assert.equal(result(d).groups[0].count, 4); });
test("zero baseline does not invent infinite growth", () => { const d = fixture(); d.observations.forEach(o => { if (d.videos.find(v => v.id === o.videoId)?.variant === "A") o.views = 0; }); const r = result(d); assert.equal(r.status, "inconclusive"); assert.equal(r.relativeLift, null); });
test("below threshold stays inconclusive", () => { const d = fixture(); d.observations.filter(o => o.checkpoint === "72h").forEach(o => { o.views = d.videos.find(v => v.id === o.videoId)?.variant === "A" ? 1000 : 1199; }); assert.equal(result(d).status, "inconclusive"); });
test("an outlier is not used in place of the median", () => { const d = fixture(); d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!.views = 1000000; assert.equal(result(d).groups[0].median, 1400); });
test("a repost of the same asset does not become another sample", () => { const d = fixture(); d.videos[4].contentHash = d.videos[0].contentHash; assert.equal(result(d).groups[1].count, 3); assert.match(result(d).excluded[0].reason, /再投稿/); });
test("a missing asset hash excludes the sample", () => { const d = fixture(); d.videos[0].contentHash = ""; assert.equal(result(d).groups[0].count, 3); });
for (const key of ["voice", "visualStyle", "series", "character", "language", "subtitleStyle"] as const) test(`different ${key} is not pooled`, () => { const d = fixture(); d.videos[0].conditions = { ...d.videos[0].conditions, [key]: "different" }; assert.equal(result(d).groups[0].count, 3); });
test("children and general audiences are never pooled", () => { const d = fixture(); d.videos[0].conditions = { ...d.videos[0].conditions, audience: "general" }; assert.equal(result(d).groups[0].count, 3); });
test("different channels and durations are excluded", () => { const d = fixture(); d.videos[0].channelId = "other"; d.videos[1].durationSeconds = 80; assert.equal(result(d).groups[0].count, 2); });
test("metadata that is no longer verified is excluded", () => { const d = fixture(); d.videos[0].verified = false; assert.equal(result(d).groups[0].count, 3); });
test("a plan cannot retrospectively claim an old publication as a planned experiment", () => { const d = fixture(); d.experiments[0].createdAt = "2026-08-11T00:00:00Z"; assert.equal(result(d).groups[0].count, 3); });
test("a day-7 observation cannot fill the 72-hour checkpoint", () => { const d = fixture(); const o = d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!; o.observedAt = new Date(Date.parse(d.videos[0].publishedAt) + 7 * 86400000).toISOString(); assert.equal(result(d).groups[0].count, 3); });
test("a pre-72-hour count cannot fill the checkpoint", () => { const d = fixture(); const o = d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!; o.observedAt = new Date(Date.parse(d.videos[0].publishedAt) + 259199000).toISOString(); assert.equal(result(d).groups[0].count, 3); });
test("different metric definitions are excluded", () => { const d = fixture(); d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!.definition = "analytics:engagedViews"; assert.equal(result(d).groups[0].count, 3); });
test("later larger observation does not replace the first observation", () => { const d = fixture(); const o = d.observations.find(o => o.videoId === d.videos[0].id && o.checkpoint === "72h")!; d.observations.push({ ...o, id: "later", observedAt: new Date(Date.parse(o.observedAt) + 10000).toISOString(), views: 1000000 }); assert.equal(result(d).groups[0].median, 1300); assert.equal(result(d).groups[0].count, 4); });
test("invalid counts are excluded", () => { for (const views of [-1, NaN, Infinity, 1.5, Number.MAX_SAFE_INTEGER + 1]) { const d = fixture(); d.observations.find(o => o.checkpoint === "72h")!.views = views; assert.equal(result(d).groups[0].count, 3); } });
for (const c of CHECKPOINTS) test(`${c.key} has explicit non-overlapping collection boundaries`, () => { const published = "2026-09-01T00:00:00Z", due = Date.parse(published) + c.seconds * 1000; assert.equal(checkpointState(published, c.key, new Date(due - 1)).state, "waiting"); assert.equal(checkpointState(published, c.key, new Date(due)).state, "due"); assert.equal(checkpointState(published, c.key, new Date(due + c.tolerance * 1000)).state, "due"); assert.equal(checkpointState(published, c.key, new Date(due + c.tolerance * 1000 + 1)).state, "missed"); });
test("comparison reports cannot use future observations", () => { const d = fixture(); const r = compare(d.experiments[0], d, "youtube_data", new Date("2026-08-14T00:00:00Z")); assert.equal(r.status, "insufficient_data"); assert.equal(r.definition, VIEW_DEFINITION); });
