import { test } from "node:test";
import assert from "node:assert/strict";
import { YouTubeClient, YouTubeError, counter, durationSeconds, pacificDay, addDays } from "../lib/youtube";
import { youtubeId, experimentInput, draftUpdateInput } from "../lib/validation";
import { DEFAULT_CONDITIONS } from "../lib/growth";
const config = { apiKey: "test-key", channelId: "UCabcdefghijklmnopqrstuv", clientId: "test-client", clientSecret: "test-secret", refreshToken: "test-refresh" };
function fake(fn: (url: string, init?: RequestInit) => Response | Promise<Response>) { return ((url: string | URL | Request, init?: RequestInit) => Promise.resolve(fn(String(url), init))) as typeof fetch; }
test("YouTube links are allowlisted, not arbitrary fetched URLs", () => { assert.equal(youtubeId("https://youtu.be/abcdefghijk"), "abcdefghijk"); assert.equal(youtubeId("https://www.youtube.com/shorts/abcdefghijk"), "abcdefghijk"); assert.equal(youtubeId("https://youtube.com/watch?v=abcdefghijk"), "abcdefghijk"); for (const url of ["https://youtube.com.evil.test/watch?v=abcdefghijk", "http://127.0.0.1", "https://user:pass@youtube.com/watch?v=abcdefghijk", "javascript:alert(1)", "bad"]) assert.equal(youtubeId(url), null); });
test("missing counters stay null while explicit zero is retained", () => { for (const v of [undefined, null, "", "bad", -1, true]) assert.equal(counter(v), null); assert.equal(counter("0"), 0); assert.equal(counter("123"), 123); });
test("ISO duration handles hours and rejects malformed durations", () => { assert.equal(durationSeconds("PT38S"), 38); assert.equal(durationSeconds("PT1H2M3S"), 3723); assert.equal(durationSeconds("unknown"), null); });
test("Analytics uses Pacific calendar dates across DST", () => { assert.equal(pacificDay(new Date("2026-03-08T07:30:00Z")), "2026-03-07"); assert.equal(addDays("2026-03-01", -1), "2026-02-28"); });
test("video metadata sends the key in a header and preserves absent likes", async () => { const client = new YouTubeClient(config, fake((url, init) => { assert.ok(!url.includes(config.apiKey)); assert.equal((init?.headers as Record<string, string>)["X-Goog-Api-Key"], config.apiKey); return Response.json({ items: [{ id: "abcdefghijk", snippet: { title: "テスト", channelId: config.channelId, publishedAt: "2026-09-01T00:00:00Z" }, contentDetails: { duration: "PT38S" }, status: { privacyStatus: "public" }, statistics: { viewCount: "0" } }] }); })); const [v] = await client.videoMetadata(["abcdefghijk"]); assert.equal(v.views, 0); assert.equal(v.likes, null); assert.equal(v.duration, 38); });
test("quota errors are typed and never expose API credentials", async () => { const client = new YouTubeClient(config, fake(() => Response.json({ error: { errors: [{ reason: "quotaExceeded" }] } }, { status: 403 }))); await assert.rejects(client.videoMetadata(["abcdefghijk"]), (error: unknown) => error instanceof YouTubeError && error.code === "quota_exceeded" && !error.message.includes(config.apiKey)); });
test("transient network failures are retryable", async () => { const client = new YouTubeClient(config, fake(() => { throw new Error("secret url"); })); await assert.rejects(client.videoMetadata(["abcdefghijk"]), (e: unknown) => e instanceof YouTubeError && e.retryable && !e.message.includes("secret")); });
test("daily Analytics maps headers, refreshes OAuth, and does not invent missing metrics", async () => { const urls: string[] = []; const client = new YouTubeClient(config, fake((url, init) => { urls.push(url); if (url.includes("oauth2")) return Response.json({ access_token: "access", expires_in: 3600 }); assert.equal((init?.headers as Record<string, string>).Authorization, "Bearer access"); assert.equal(new URL(url).searchParams.get("endDate"), "2026-09-07"); return Response.json({ columnHeaders: [{ name: "day" }, { name: "averageViewPercentage" }, { name: "engagedViews" }], rows: [["2026-09-01", 110.2, 24]] }); })); const rows = await client.dailyAnalytics("video", "abcdefghijk", "2026-09-01T12:00:00Z", new Date("2026-09-10T12:00:00Z")); assert.equal(rows[0].engagedViews, 24); assert.equal(rows[0].views, null); assert.equal(rows[0].averageViewPercentage, 110.2); await client.dailyAnalytics("video", "abcdefghijk", "2026-09-01T12:00:00Z", new Date("2026-09-10T12:00:00Z")); assert.equal(urls.filter(u => u.includes("oauth2")).length, 1); });
test("Analytics with no available rows yields no synthetic daily zeros", async () => { const client = new YouTubeClient(config, fake(url => Response.json(url.includes("oauth2") ? { access_token: "access" } : { columnHeaders: [{ name: "day" }], rows: [] }))); assert.deepEqual(await client.dailyAnalytics("v", "abcdefghijk", "2026-09-01T12:00:00Z", new Date("2026-09-10T12:00:00Z")), []); });
test("an unconfigured OAuth connection never calls the Analytics endpoint", async () => { const client = new YouTubeClient({ ...config, refreshToken: "" }, fake(() => { assert.fail("must not fetch"); })); await assert.rejects(client.dailyAnalytics("v", "abcdefghijk", "2026-09-01T12:00:00Z", new Date("2026-09-10T12:00:00Z")), /authorization_required/); });
test("input cannot override plan creation dates or permissions", () => { const plan = { title: "test", channelId: config.channelId, conditions: DEFAULT_CONDITIONS, variantA: "質問から始める", variantB: "見せ場を先に出す", minSamples: 4, threshold: .2 }; assert.equal(experimentInput.safeParse(plan).success, true); assert.equal(experimentInput.safeParse({ ...plan, createdAt: "2000-01-01" }).success, false); assert.equal(experimentInput.safeParse({ ...plan, minSamples: 1 }).success, false); assert.equal(draftUpdateInput.safeParse({ status: "reviewed", evidence: { publish: true } }).success, false); });
