"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Activity, ArrowDownToLine, ArrowRight, BarChart3, Check, CheckCircle2, ChevronRight, Clock3, FlaskConical, Link2, Loader2, Play, Plus, RefreshCw, Settings2, Sparkles, Video as VideoIcon, FileText } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { toast, Toaster } from "sonner";
import { CHECKPOINTS, DEFAULT_CONDITIONS, EMPTY_DATA, checkpointState, compare, draftScript, type Draft, type Experiment, type StudioData, type Video } from "@/lib/growth";
import { makeDemo } from "@/lib/demo";

type Connection = { dataApi: boolean; analytics: boolean; channelId: string | null; lastRun: { finishedAt: string; summary: string } | null };
const number = (v: number | null | undefined) => v == null ? "—" : v.toLocaleString("ja-JP", { maximumFractionDigits: 1 });
const date = (v: string) => new Date(v).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo", month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" });
const statusLabel = { retest_candidate: "再検証の候補", insufficient_data: "データ収集中", inconclusive: "判断保留" };

function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
function Choice({ value, onChange, items, label }: { value: string; onChange: (v: string) => void; items: [string, string][]; label: string }) { return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue placeholder={label} /></SelectTrigger><SelectContent>{items.map(([id, title]) => <SelectItem key={id} value={id}>{title}</SelectItem>)}</SelectContent></Select>; }
function Blank({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <Empty className="blank"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader>{action}</Empty>; }
function exportJson(value: unknown, filename: string) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function request<T = unknown>(path: string, body?: unknown, method = "POST") {
  const response = await fetch(`/api/${path}`, { method: body === undefined ? "GET" : method, headers: body === undefined ? {} : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(data.error ?? "処理に失敗しました。もう一度お試しください。");
  return data;
}

export default function Studio() {
  const [demo, setDemo] = useState(true);
  const [demoData, setDemoData] = useState<StudioData>(() => makeDemo());
  const [realData, setRealData] = useState<StudioData>(EMPTY_DATA);
  const [connection, setConnection] = useState<Connection | null>(null);
  const [authenticated, setAuthenticated] = useState(false);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState("");
  const [tab, setTab] = useState("overview");
  const [selected, setSelected] = useState("");
  const [modal, setModal] = useState<"experiment" | "video" | "draft" | null>(null);
  const [detail, setDetail] = useState<Video | null>(null);
  const [busy, setBusy] = useState(false);
  const data = demo ? demoData : realData;
  const experiment = data.experiments.find(e => e.id === selected) ?? data.experiments[0];
  const result = useMemo(() => experiment ? compare(experiment, data, demo ? "demo" : "youtube_data") : null, [experiment, data, demo]);
  const videos = experiment ? data.videos.filter(v => v.experimentId === experiment.id) : data.videos;
  const refresh = useCallback(async () => {
    setLoading(true); setLoadError("");
    try {
      const res = await fetch("/api/state");
      if (res.status === 401) { setAuthenticated(false); return; }
      const body = await res.json() as { error?: string; data: StudioData; connection: Connection };
      if (!res.ok) throw new Error(body.error ?? "データを読み込めませんでした。");
      setAuthenticated(true); setRealData(body.data); setConnection(body.connection);
    } catch (error) { setLoadError((error as Error).message); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  async function collect() {
    setBusy(true);
    try { const response = await request<{ summary: string }>("collect", {}); toast.success(response.summary); await refresh(); }
    catch (error) { toast.error((error as Error).message); }
    finally { setBusy(false); }
  }
  function changeMode(value: boolean) { setDemo(value); setSelected(""); setDetail(null); if (!value) void refresh(); }
  const eligible = result?.groups.reduce((sum, g) => sum + g.count, 0) ?? 0;
  const pending = videos.flatMap(v => CHECKPOINTS.map(c => ({ v, c, ...checkpointState(v.publishedAt, c.key, new Date()) }))).filter(p => p.state !== "missed" && !data.observations.some(o => o.videoId === p.v.id && o.checkpoint === p.c.key)).sort((a, b) => a.due.localeCompare(b.due));
  return <div className="studio-shell">
    <Toaster position="bottom-right" richColors />
    <header className="masthead"><a className="brand" href="/" aria-label="Growth Studio ホーム"><span className="brand-icon"><Play size={19} fill="currentColor" /></span><span>Growth<span className="brand-light"> Studio</span></span></a><div className="header-right"><span className="workspace-label">YouTube ワークスペース</span><span className="avatar">GS</span></div></header>
    <main className="workspace">
      <div className="page-heading"><div><p className="eyebrow">CREATE. MEASURE. LEARN.</p><h1>次の一本を、もっとよく。</h1><p className="intro">投稿の結果を、次の動画の制作指示へ。</p></div><div className="mode-control" aria-label="表示するデータ"><button className={!demo ? "active" : ""} onClick={() => changeMode(false)}>実データ</button><button className={demo ? "active" : ""} onClick={() => changeMode(true)}><FlaskConical size={15} />デモ</button></div></div>
      {demo ? <div className="demo-banner"><FlaskConical size={17} /><span><strong>デモを表示中</strong>　架空の8本で改善の流れを確認できます。実際の投稿・実績ではありません。</span><button onClick={() => changeMode(false)}>自分の動画で始める<ArrowRight size={15} /></button></div> : <div className="live-banner"><span><Link2 size={16} />{connection?.dataApi ? "YouTube Data API 設定済み" : "YouTube接続を設定すると計測を始められます"}</span><button onClick={() => setTab("settings")}>接続設定<ChevronRight size={16} /></button></div>}
      <Tabs value={tab} onValueChange={setTab}>
        <div className="nav-row"><TabsList variant="line" className="main-tabs">{[["overview", "概要", BarChart3], ["videos", "動画と計測", VideoIcon], ["experiments", "比較と改善", FlaskConical], ["drafts", "次作の下書き", FileText], ["settings", "接続設定", Settings2]].map(([id, label, Icon]) => { const I = Icon as typeof BarChart3; return <TabsTrigger key={id as string} value={id as string}><I size={16} />{label as string}</TabsTrigger>; })}</TabsList><span className="timezone">時刻は日本時間</span></div>
        {!demo && loadError && <div className="error-banner" role="alert">{loadError}<button onClick={() => void refresh()}>再読み込み</button></div>}
        {!demo && !authenticated && !loading && !loadError && <div className="auth-banner"><span>動画や下書きの保存にはサインインが必要です。</span><a className="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">サインイン</a></div>}
        {!demo && loading && <div role="status" className="loading-line"><Loader2 size={16} className="spin" />実データを読み込み中…</div>}
        {tab !== "settings" && tab !== "drafts" && <div className="section-toolbar"><div className="experiment-selector"><span className="small-label">比較計画</span>{experiment ? <Choice label="比較計画を選択" value={experiment.id} onChange={setSelected} items={data.experiments.map(e => [e.id, e.title])} /> : <span className="muted">まだありません</span>}</div><button className="button secondary" disabled={demo || !authenticated} onClick={() => setModal("experiment")}><Plus size={16} />比較計画を作成</button></div>}
        <TabsContent value="overview">
          <div className="metrics-grid"><Metric label="登録した動画" value={String(videos.length)} suffix="本" note={experiment?.conditions.series ?? "比較計画を作成して始める"} icon={<VideoIcon size={18} />} /><Metric label="比較に使える72時間計測" value={String(eligible)} suffix="本" note={result ? `A ${result.groups[0].count}本 / B ${result.groups[1].count}本` : "未計測をゼロに置き換えません"} icon={<Activity size={18} />} /><Metric label="次の判断" value={result ? statusLabel[result.status] : "計画を作成"} note={result?.status === "retest_candidate" ? "別の話でも同じ傾向かを確認" : "A / B 各4本から比較"} icon={<FlaskConical size={18} />} /></div>
          <div className="overview-grid"><section className="panel comparison-panel"><div className="panel-heading"><div><p className="eyebrow">EXPERIMENT / 01</p><h2>冒頭が変わると、結果は？</h2></div><span className="tag">公開72時間後</span></div>{result && experiment ? <><p className="muted chart-subtitle">{experiment.conditions.series} · {experiment.conditions.durationMin}〜{experiment.conditions.durationMax}秒 · 再生数の中央値</p><ComparisonChart result={result} /><div className="chart-foot"><span>同じ条件・出典の動画だけを比較</span><button onClick={() => setTab("experiments")}>根拠を見る<ArrowRight size={15} /></button></div></> : <Blank title="最初の比較計画を作りましょう" text="シリーズ、声、尺を揃えて、冒頭の見せ方を一つだけ変えます。" action={<button className="button primary" disabled={!authenticated || demo} onClick={() => setModal("experiment")}>比較計画を作成</button>} />}</section>
            <section className="next-panel"><div className="next-panel-top"><Sparkles size={20} /><span>NEXT EPISODE</span></div><h2>{result?.status === "retest_candidate" ? <>次は、<br />「{result.groups.find(g => g.variant === result.candidate)?.label}」を。</> : <>まずは、<br />判断できる材料を。</>}</h2><p>{result?.nextChange ?? "一本の投稿から計測を始めましょう。比較に必要な条件を先に揃えます。"}</p><div className="next-panel-bottom"><span>{result?.status === "retest_candidate" ? "観察結果に基づく再検証案" : "優劣の判断はデータが揃ってから"}</span><button className="button light" disabled={!result || result.status !== "retest_candidate"} onClick={() => setModal("draft")}>改善を下書きに反映<ArrowRight size={16} /></button></div></section></div>
          <section className="panel recent-panel"><div className="panel-heading"><h2>動画の計測状況</h2><button className="text-button" onClick={() => setTab("videos")}>すべて見る<ArrowRight size={15} /></button></div><VideoTable videos={videos.slice(0, 4)} data={data} onDetail={setDetail} /></section>
          <div className="bottom-note"><Clock3 size={16} /><span>{pending[0] ? `次の計測予定：${date(pending[0].due)} · ${pending[0].v.title}（${pending[0].c.label}）` : "計測時点：公開15分・1時間・24時間・72時間・7日後"}</span><span>取り逃した計測は「欠測」として記録</span></div>
        </TabsContent>
        <TabsContent value="videos"><section className="panel"><div className="panel-heading"><div><h2>動画と計測</h2><p className="muted">完成素材と、公開後の観測値を結び付けます。</p></div><div className="actions"><button className="button secondary" disabled={demo || busy || !authenticated} onClick={collect}>{busy ? <Loader2 size={16} className="spin" /> : <RefreshCw size={16} />}今すぐ収集</button><button className="button primary" disabled={demo || !authenticated || !experiment} onClick={() => setModal("video")}><Plus size={16} />公開済み動画を登録</button></div></div><VideoTable videos={videos} data={data} onDetail={setDetail} />{!videos.length && <Blank title="まだ動画が登録されていません" text="YouTube Studioから公開した動画のURLと、完成MP4を登録してください。" />}</section><p className="help-text">動画名を選ぶと、観測時刻・欠測理由・日別の視聴状況を確認できます。</p></TabsContent>
        <TabsContent value="experiments">{result && experiment ? <><div className="comparison-layout"><section className="panel"><div className="panel-heading"><h2>{experiment.title}</h2><span className="tag">{statusLabel[result.status]}</span></div><ComparisonChart result={result} /><div className="conditions"><h3>揃える条件</h3><dl>{[["シリーズ", experiment.conditions.series], ["対象", experiment.conditions.audience === "kids" ? "子ども向け" : "一般向け"], ["声", experiment.conditions.voice], ["尺", `${experiment.conditions.durationMin}〜${experiment.conditions.durationMax}秒`], ["画風", experiment.conditions.visualStyle], ["キャラクター", experiment.conditions.character], ["字幕", experiment.conditions.subtitleStyle]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></section><section className="panel evidence-panel"><p className="eyebrow">EVIDENCE → NEXT STEP</p><h2>観測と、次の変更を分ける。</h2><h3>01 観測したこと</h3>{result.facts.map(f => <p key={f}>{f}</p>)}<h3>02 まだ分からないこと</h3>{result.uncertainties.map(u => <p key={u}>{u}</p>)}<h3>03 次に変えること</h3><p>{result.nextChange}</p><div className="actions"><button className="button secondary" onClick={() => exportJson(result, "improvement-evidence.json")}><ArrowDownToLine size={16} />根拠JSON</button><button className="button primary" disabled={result.status !== "retest_candidate"} onClick={() => setModal("draft")}>下書きに反映<ArrowRight size={16} /></button></div></section></div><section className="panel audit-panel"><h3>比較から除外した動画 · {result.excluded.length}本</h3>{result.excluded.length ? result.excluded.map(e => <p key={e.videoId}>{data.videos.find(v => v.id === e.videoId)?.title} <span className="muted">— {e.reason}</span></p>) : <p className="muted">今回の比較では、すべての動画が条件を満たしています。</p>}<details><summary>使用した観測IDを表示</summary><pre>{result.groups.map(g => `${g.variant}: ${g.observationIds.join("\n")}`).join("\n\n")}</pre></details></section></> : <Blank title="比較計画を作成してください" text="結果を見る前に、変える要素と固定する条件を決めます。" />}</TabsContent>
        <TabsContent value="drafts"><div className="panel-heading standalone"><div><h2>次作の下書き</h2><p className="muted">比較の根拠を引き継いで、別のエピソードへ。</p></div><span className="tag">{data.drafts.length}件</span></div>{data.drafts.length ? <div className="draft-grid">{data.drafts.map(d => <DraftCard key={d.id} draft={d} demo={demo} onSave={async (script) => { if (demo) setDemoData(prev => ({ ...prev, drafts: prev.drafts.map(item => item.id === d.id ? { ...item, script, status: "draft", revision: item.revision + 1 } : item) })); else { await request(`drafts/${d.id}`, { script, expectedRevision: d.revision }, "PATCH"); await refresh(); } }} onReview={async () => { if (demo) setDemoData(prev => ({ ...prev, drafts: prev.drafts.map(item => item.id === d.id ? { ...item, status: "reviewed", revision: item.revision + 1 } : item) })); else { await request(`drafts/${d.id}`, { status: "reviewed", expectedRevision: d.revision }, "PATCH"); await refresh(); } }} />)}</div> : <Blank title="次の一本は、ここから。" text="比較で再検証の候補が見つかったら、根拠と変更点を下書きに引き継げます。" action={<button className="button secondary" onClick={() => setTab("experiments")}>比較と改善を見る<ArrowRight size={16} /></button>} />}</TabsContent>
        <TabsContent value="settings"><div className="settings-grid"><section className="panel settings-panel"><p className="eyebrow">CONNECTIONS</p><h2>YouTubeとの接続</h2><p className="muted">公開動画の統計と、自分のチャンネルの詳細分析を読み取ります。</p><ConnectionRow title="公開動画の統計" text="再生数・高評価・公開日時の確認" ready={connection?.dataApi ?? false} /><ConnectionRow title="チャンネルの詳細分析" text="エンゲージビュー・平均視聴時間・共有・登録" ready={connection?.analytics ?? false} /><div className="setup-instructions"><h3>接続の準備</h3><ol><li>Google CloudでYouTube Data APIとYouTube Analytics APIを有効にします。</li><li>プロジェクトの環境設定にAPIキーとチャンネルIDを設定します。</li><li>同梱の認可ツールで、自分のチャンネルの読み取りを許可します。</li><li>収集プロセスを起動し、公開済み動画を登録します。</li></ol><p>接続情報はサーバー側で管理します。手順の詳細はプロジェクトのREADMEをご覧ください。</p><button className="button secondary" onClick={() => void refresh()} disabled={loading}><RefreshCw size={16} />接続状態を再確認</button></div></section><div><section className="panel settings-panel"><h2>収集の状態</h2><p className="muted">{connection?.lastRun ? `${date(connection.lastRun.finishedAt)} · ${connection.lastRun.summary}` : "収集履歴はまだありません。"}</p><div className="checkpoint-list">{CHECKPOINTS.map(c => <div key={c.key}><Clock3 size={16} /><span>公開{c.label}後</span><span>許容遅延 {c.tolerance / 60}分</span></div>)}</div><p className="help-text">定期収集は同梱のワーカープロセスで実行します。画面を開いていなくても、プロセスの稼働中は計測できます。</p></section><section className="panel settings-panel"><h3>実データとデモは別々に管理</h3><p className="muted">デモの編集内容は画面を再読み込みするとリセットされます。実データの動画・観測値・下書きはサーバーに保存します。</p></section></div></div></TabsContent>
      </Tabs>
      <footer className="footer"><span className="footer-brand">Growth Studio</span><span>小さく試して、根拠を残して、次の一本へ。</span></footer>
    </main>
    <Dialog open={modal !== null} onOpenChange={open => { if (!open && !busy) setModal(null); }}><DialogContent className="studio-dialog"><DialogHeader><DialogTitle>{modal === "experiment" ? "比較計画を作成" : modal === "video" ? "公開済み動画を登録" : "改善を次作に反映"}</DialogTitle><DialogDescription>{modal === "experiment" ? "投稿前に固定条件を決めます。変更する要素は冒頭だけです。" : modal === "video" ? "YouTubeから公開日時・尺・チャンネルを確認して保存します。" : "別のエピソード名を入力して、冒頭の変更と根拠を引き継ぎます。"}</DialogDescription></DialogHeader>{modal === "experiment" && <ExperimentForm channelId={connection?.channelId ?? ""} onSave={async body => { const e = await request<{ id: string }>("experiments", body); await refresh(); setSelected(e.id); setModal(null); }} />}{modal === "video" && experiment && <VideoForm experiment={experiment} onSave={async body => { await request("videos", body); await refresh(); setModal(null); toast.success("公開済み動画を登録しました。"); }} />}{modal === "draft" && experiment && result && <DraftForm onSave={async title => { if (demo) { const d: Draft = { id: crypto.randomUUID(), title, experimentId: experiment.id, status: "draft", revision: 1, script: draftScript(experiment, result, title), evidence: result, createdAt: new Date().toISOString() }; setDemoData(prev => ({ ...prev, drafts: [...prev.drafts, d] })); } else { await request("drafts", { experimentId: experiment.id, title }); await refresh(); } setModal(null); setTab("drafts"); }} />}</DialogContent></Dialog>
    <Dialog open={Boolean(detail)} onOpenChange={open => { if (!open) setDetail(null); }}><DialogContent className="studio-dialog detail-dialog"><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>公開 {detail ? date(detail.publishedAt) : ""} · 計測値は取得時刻の累積値です。</DialogDescription></DialogHeader>{detail && <VideoDetail video={detail} data={data} demo={demo} />}</DialogContent></Dialog>
  </div>;
}
function Metric({ label, value, suffix, note, icon }: { label: string; value: string; suffix?: string; note: string; icon: ReactNode }) { return <section className="metric"><div className="metric-label">{label}{icon}</div><div className={`metric-value ${value.length > 5 ? "text-value" : ""}`}>{value}<span>{suffix}</span></div><p>{note}</p></section>; }
function ComparisonChart({ result }: { result: ReturnType<typeof compare> }) { const maximum = Math.max(...result.groups.map(g => g.median ?? 0), 1); return <div className="comparison-chart">{result.groups.map(g => <div className="comparison-bar" key={g.variant}><div className="bar-label"><span className={`variant variant-${g.variant}`}>{g.variant}</span><span>{g.label}<small>有効な計測 {g.count}本</small></span><strong>{number(g.median)}<small>回</small></strong></div><div className="bar-track"><div className={`bar-fill fill-${g.variant}`} style={{ width: `${(g.median ?? 0) / maximum * 100}%` }} /></div></div>)}<div className="comparison-verdict">{result.relativeLift !== null ? <><span className="lift">{(result.relativeLift * 100).toFixed(1)}<small>%</small></span><span>中央値の差<span className="muted">{statusLabel[result.status]} · 因果関係は未確認</span></span></> : <p className="muted">有効な計測が揃うまで増加率を表示しません。</p>}</div></div>; }
function VideoTable({ videos, data, onDetail }: { videos: Video[]; data: StudioData; onDetail: (v: Video) => void }) { return <Table className="video-table"><TableHeader><TableRow><TableHead>動画</TableHead><TableHead>案</TableHead><TableHead>公開日時</TableHead><TableHead className="numeric">24時間</TableHead><TableHead className="numeric">72時間</TableHead><TableHead>計測状況</TableHead></TableRow></TableHeader><TableBody>{videos.map((v, i) => { const at = (key: string) => data.observations.find(o => o.videoId === v.id && o.checkpoint === key); const o = at("72h"); return <TableRow key={v.id}><TableCell><button className="video-title" onClick={() => onDetail(v)}><span className={`video-tile tile-${v.variant}`}><Play size={18} /><small>{String(i + 1).padStart(2, "0")}</small></span><span>{v.title}<small>{v.durationSeconds}秒 · {v.conditions.series}</small></span></button></TableCell><TableCell><span className={`variant variant-${v.variant}`}>{v.variant}</span></TableCell><TableCell className="muted">{date(v.publishedAt)}</TableCell><TableCell className="numeric">{number(at("24h")?.views)}</TableCell><TableCell className="numeric strong">{number(o?.views)}</TableCell><TableCell><span className={`measurement ${o?.status === "collected" ? "complete" : ""}`}>{o?.status === "collected" ? <CheckCircle2 size={14} /> : <Clock3 size={14} />}{o?.status === "collected" ? "72時間 計測済み" : o?.status === "missed" || checkpointState(v.publishedAt, "72h", new Date()).state === "missed" ? "72時間 欠測" : "計測待ち"}</span></TableCell></TableRow>; })}</TableBody></Table>; }
function ConnectionRow({ title, text, ready }: { title: string; text: string; ready: boolean }) { return <div className="connection-row"><span className="connection-icon"><Link2 size={18} /></span><div><strong>{title}</strong><p>{text}</p></div><span className={`tag ${ready ? "connected" : ""}`}>{ready ? "設定済み" : "未設定"}</span></div>; }
function AsyncForm({ children, onSubmit, label }: { children: ReactNode; onSubmit: (form: HTMLFormElement) => Promise<void>; label: string }) { const [saving, setSaving] = useState(false), [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setSaving(true); setError(""); try { await onSubmit(form); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } } return <form className="studio-form" onSubmit={submit}>{children}{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary submit" disabled={saving} type="submit">{saving && <Loader2 size={16} className="spin" />}{saving ? "保存中…" : label}</button></form>; }
function ExperimentForm({ channelId, onSave }: { channelId: string; onSave: (body: unknown) => Promise<void> }) { const [audience, setAudience] = useState("kids"), [format, setFormat] = useState("short"); return <AsyncForm label="比較計画を保存" onSubmit={async form => { const f = new FormData(form); await onSave({ title: f.get("title"), channelId: f.get("channelId"), conditions: { ...DEFAULT_CONDITIONS, series: f.get("series"), audience, format, voice: f.get("voice"), visualStyle: f.get("visualStyle"), character: f.get("character"), subtitleStyle: f.get("subtitleStyle"), durationMin: Number(f.get("durationMin")), durationMax: Number(f.get("durationMax")) }, variantA: "質問から始める", variantB: "見せ場を先に出す", minSamples: 4, threshold: .2 }); }}><Field label="計画名"><input name="title" required maxLength={120} defaultValue="冒頭の見せ方を比べる" /></Field><Field label="YouTubeチャンネルID"><input name="channelId" required pattern="UC[A-Za-z0-9_-]{22}" defaultValue={channelId} placeholder="UCから始まるチャンネルID" /></Field><Field label="シリーズ"><input name="series" defaultValue={DEFAULT_CONDITIONS.series} required maxLength={120} /></Field><div className="form-columns"><Field label="対象視聴者"><Choice label="対象視聴者" value={audience} onChange={setAudience} items={[["kids", "子ども向け"], ["general", "一般向け"]]} /></Field><Field label="動画の形式"><Choice label="動画の形式" value={format} onChange={setFormat} items={[["short", "ショート"], ["standard", "通常動画"]]} /></Field></div><div className="form-columns"><Field label="最短の尺（秒）"><input type="number" name="durationMin" defaultValue={30} min={1} max={600} required /></Field><Field label="最長の尺（秒）"><input type="number" name="durationMax" defaultValue={45} min={1} max={600} required /></Field></div>{[["voice", "声", DEFAULT_CONDITIONS.voice], ["visualStyle", "画風", DEFAULT_CONDITIONS.visualStyle], ["character", "キャラクター", DEFAULT_CONDITIONS.character], ["subtitleStyle", "字幕", DEFAULT_CONDITIONS.subtitleStyle]].map(([name, label, value]) => <Field key={name} label={label}><input name={name} defaultValue={value} maxLength={150} required /></Field>)}<p className="form-note">A：質問から始める / B：見せ場を先に出す<br />各4本・72時間後の中央値・差20%以上で再検証候補。計画の保存後に公開した動画を比較します。</p></AsyncForm>; }
function VideoForm({ experiment, onSave }: { experiment: Experiment; onSave: (body: unknown) => Promise<void> }) { const [variant, setVariant] = useState("A"), [hash, setHash] = useState(""), [hashError, setHashError] = useState(""); return <AsyncForm label="公開状態を確認して登録" onSubmit={async form => { const f = new FormData(form); await onSave({ experimentId: experiment.id, youtubeUrl: f.get("youtubeUrl"), variant, episode: f.get("episode"), contentHash: hash }); }}><Field label="公開した動画のURL"><input name="youtubeUrl" required placeholder="https://www.youtube.com/shorts/…" /></Field><Field label="今回のエピソード"><input name="episode" required maxLength={150} placeholder="例：あおいボールをさがす" /></Field><Field label="冒頭の案"><Choice label="冒頭の案" value={variant} onChange={setVariant} items={[["A", `A：${experiment.variantA}`], ["B", `B：${experiment.variantB}`]]} /></Field><Field label="完成MP4" hint="素材の重複確認に使用します。動画ファイルはアップロードせず、この端末でハッシュを計算します（256MBまで）。"><input type="file" accept="video/mp4,.mp4" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; setHash(""); setHashError(""); if (file.size > 256 * 1024 * 1024) { setHashError("256MBを超える場合は、SHA-256を下の欄に入力してください。"); return; } try { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); setHash(Array.from(new Uint8Array(digest)).map(v => v.toString(16).padStart(2, "0")).join("")); } catch { setHashError("ハッシュを計算できませんでした。SHA-256を直接入力してください。"); } }} /></Field>{hashError && <p role="alert" className="form-error">{hashError}</p>}<Field label="素材のSHA-256"><input value={hash} onChange={e => setHash(e.target.value.toLowerCase())} required pattern="[a-f0-9]{64}" placeholder="64文字のハッシュ（ファイル選択で自動入力）" /></Field><p className="form-note">固定条件：{experiment.conditions.series} / {experiment.conditions.voice} / {experiment.conditions.durationMin}〜{experiment.conditions.durationMax}秒。実際の動画がこれらの条件と一致することを確認してください。</p></AsyncForm>; }
function DraftForm({ onSave }: { onSave: (title: string) => Promise<void> }) { return <AsyncForm label="下書きを作成" onSubmit={async form => { await onSave(String(new FormData(form).get("title"))); }}><Field label="次に扱う、別のエピソード"><input name="title" required maxLength={150} placeholder="例：みどりのはっぱ" /></Field><p className="form-note">制作指示と台本のたたき台を作成します。動画や音声の生成は後の制作工程で行います。</p></AsyncForm>; }
function DraftCard({ draft, demo, onSave, onReview }: { draft: Draft; demo: boolean; onSave: (script: string) => Promise<void>; onReview: () => Promise<void> }) { const [script, setScript] = useState(draft.script), [saving, setSaving] = useState(false); async function act(task: () => Promise<void>) { setSaving(true); try { await task(); toast.success(demo ? "デモ内で更新しました。" : "保存しました。"); } catch (e) { toast.error((e as Error).message); } finally { setSaving(false); } } return <section className="panel draft-card"><div className="panel-heading"><h3>{draft.title}</h3><span className="tag">{draft.status === "reviewed" ? "台本確認済み" : "下書き"}</span></div><p className="draft-change">変更する要素：冒頭 · {draft.evidence.candidate}案を別の話で再検証</p><textarea aria-label={`${draft.title}の台本`} value={script} onChange={e => setScript(e.target.value)} rows={14} maxLength={20000} /><div className="actions"><button className="button secondary" onClick={() => exportJson({ ...draft, script, status: script === draft.script ? draft.status : "draft" }, "next-episode.json")}><ArrowDownToLine size={16} />JSON</button><button className="button secondary" disabled={saving || script === draft.script} onClick={() => void act(() => onSave(script))}>台本を保存</button><button className="button primary" disabled={saving || script !== draft.script || draft.status === "reviewed"} onClick={() => void act(onReview)}><Check size={16} />台本を確認済みに</button></div><p className="help-text">台本の確認は、動画の公開許可にはなりません。</p></section>; }
function VideoDetail({ video, data, demo }: { video: Video; data: StudioData; demo: boolean }) { const rows = data.analytics.filter(a => a.videoId === video.id); return <div className="video-detail">{!demo && <a className="text-button" href={`https://www.youtube.com/watch?v=${video.youtubeId}`} target="_blank" rel="noreferrer">YouTubeで開く<ArrowRight size={15} /></a>}<Table><TableHeader><TableRow><TableHead>計測点</TableHead><TableHead>観測時刻</TableHead><TableHead>再生数</TableHead><TableHead>状態</TableHead></TableRow></TableHeader><TableBody>{CHECKPOINTS.map(c => { const o = data.observations.find(o => o.videoId === video.id && o.checkpoint === c.key); return <TableRow key={c.key}><TableCell>{c.label}</TableCell><TableCell>{o ? date(o.observedAt) : "—"}</TableCell><TableCell>{number(o?.views)}</TableCell><TableCell>{o?.status === "missed" ? `欠測：${o.reason}` : o ? "取得済み" : checkpointState(video.publishedAt, c.key, new Date()).state === "missed" ? "欠測（未記録）" : "待機中"}</TableCell></TableRow>; })}</TableBody></Table><h3>日別の視聴状況</h3><p className="help-text">YouTubeの太平洋時間の日付です。平均視聴率は完視聴した人数の割合ではありません。</p>{rows.length ? <Table><TableHeader><TableRow><TableHead>日付</TableHead><TableHead>エンゲージビュー</TableHead><TableHead>平均視聴時間</TableHead><TableHead>平均視聴率</TableHead><TableHead>共有</TableHead><TableHead>登録</TableHead></TableRow></TableHeader><TableBody>{rows.map(a => <TableRow key={a.day}><TableCell>{a.day}</TableCell><TableCell>{number(a.engagedViews)}</TableCell><TableCell>{number(a.averageViewDuration)}秒</TableCell><TableCell>{number(a.averageViewPercentage)}%</TableCell><TableCell>{number(a.shares)}</TableCell><TableCell>{number(a.subscribersGained)}</TableCell></TableRow>)}</TableBody></Table> : <p className="muted">まだ取得されていません。詳細分析には認可と処理時間が必要です。</p>}<details><summary>素材と計測の識別情報</summary><pre>{JSON.stringify({ youtubeId: video.youtubeId, contentHash: video.contentHash, source: demo ? "demo" : "youtube_data", observations: data.observations.filter(o => o.videoId === video.id) }, null, 2)}</pre></details></div>; }
