import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";
export const experiments = sqliteTable("experiments", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), payload: text("payload").notNull(), createdAt: text("created_at").notNull() }, t => [index("idx_experiments_owner").on(t.ownerId)]);
export const videos = sqliteTable("videos", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), experimentId: text("experiment_id").notNull().references(() => experiments.id), youtubeId: text("youtube_id").notNull(), payload: text("payload").notNull(), createdAt: text("created_at").notNull() }, t => [uniqueIndex("idx_videos_owner_youtube").on(t.ownerId, t.youtubeId), index("idx_videos_experiment").on(t.experimentId)]);
export const observations = sqliteTable("observations", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), videoId: text("video_id").notNull().references(() => videos.id), checkpoint: text("checkpoint").notNull(), payload: text("payload").notNull() }, t => [uniqueIndex("idx_observations_video_checkpoint").on(t.videoId, t.checkpoint), index("idx_observations_owner").on(t.ownerId)]);
export const analytics = sqliteTable("analytics", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), videoId: text("video_id").notNull().references(() => videos.id), day: text("day").notNull(), payload: text("payload").notNull() }, t => [uniqueIndex("idx_analytics_video_day").on(t.videoId, t.day), index("idx_analytics_owner").on(t.ownerId)]);
export const drafts = sqliteTable("drafts", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), experimentId: text("experiment_id").notNull().references(() => experiments.id), payload: text("payload").notNull(), createdAt: text("created_at").notNull() }, t => [index("idx_drafts_owner").on(t.ownerId)]);
export const collectionRuns = sqliteTable("collection_runs", { id: text("id").primaryKey(), ownerId: text("owner_id").notNull(), finishedAt: text("finished_at").notNull(), summary: text("summary").notNull() }, t => [index("idx_collection_runs_owner_finished").on(t.ownerId, t.finishedAt)]);
export const collectorLocks = sqliteTable("collector_locks", { ownerId: text("owner_id").primaryKey(), token: text("token").notNull(), expiresAt: integer("expires_at").notNull() });
export const analyticsAttempts = sqliteTable("analytics_attempts", { videoId: text("video_id").primaryKey().references(() => videos.id), attemptedAt: text("attempted_at").notNull() });
